language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
cache: pip
script: pytest
install:
  - pip install -r requirements.txt
deploy:
  provider: pypi
  user: coolacid
  password:
    secure: FSyjLb40wxofo4zcHpbRXWCibShqYqK3q2f4iQJ/AMuhm3plbGoDXyKwMRjSxt9OSF3FwHr9XzQJptHGuctqcqKegCXo+Ov3ThdAqLRD7kVaYo6fQZRUpRDnUNtRDc/FpCk4q5cG0qa/Cl3D2jkFuchqRy7yrwzLiylNw1S6dZTFS7n6GEB7xrGAjp9wwL8JM28eoep9zzASr/suooEsUiFR9yIbcg24gCwVMBlLUr33EvNwsaMuMcLuu6x0AEmCOyUTkzOe1FiFGuSaZjN7sjYEqfHAEoENhZ/dzAYA8lfCC6fHEdtmtIIA0rmY1l1LrdNaUyR+iG/M30k8yChj6Lwup4wqbamayoo7AzaAqHuyMxQ/6hBUdU12ngloqYwJfZLch2hvDqkNi+SfF0M0mmcSF5AwuzKcKbZduwwvgI0r9TFXOkDFz4IbCOT0+KGkWOk0dDnGN3QrpVneJ3eemBLBBI552n7NwY0iXpjpVs1j+c/QQAr8hIyKXHGYZDWrIp93mNm42q9+LiY2BESpb1wyljhrKI+uwaLnsGPp5GzyHyCJVlQfZV5UAFSeyCldFL5tCkqwel/ScBjbwxTjG7i6ulxqb/VfXUt90/cYMRXh4vdGJOnbBFE7j4uS1gvOE4e1eGq2FjY0b6qrhoRHyKYGWnNbzfU+zVtGy0ICBf0=
  on:
    tags: true
